### ISSUE TITLE
M4 - A1 - Develop connection to the D-REC API

### ISSUE THREAD

**Issue by renovus** [Renovus-Tech/solarec-java#4]
API description D-REC: https://api.drecs.org/swagger/

Information on the API: https://drecs.org/wp-content/uploads/2022/12/The-D-REC-Code-.pdf

Steps:

1. Create user for Renovus SolarRec and use credentials for authentication
2. Register Organization (one organization per country)
3. Register device (inverter)
4. Add device to device group

**Comment by pferrariuy** [comment]
All required methods and code are coded. Due to lack of information to continue testing, development on halt.
