### ISSUE TITLE
M5 - A2 - Develop benchmarking methods and graphics.

### ISSUE THREAD

**Issue by renovus** [Renovus-Tech/solarec-java#7]
This will help users compare their production to other similar plants with similar radiation levels

Test features with users, sampling whether alerts work properly with in-depth fault analysis in 90% of tests

**Comment by pferrariuy** [comment]
Code exists with endpoints that will call the different Chart (pythons) endpoints that will provide the information for the different UI.

URL's of endpoints to call are stored in the application.propergies files as:

```properties
tech.renovus.solarec.python.overview.url
tech.renovus.solarec.python.performanceIndex.url
tech.renovus.solarec.python.climate.url
tech.renovus.solarec.python.powerCurve.url
tech.renovus.solarec.python.solarSales.url
tech.renovus.solarec.python.solarCertificate.url
tech.renovus.solarec.python.emissons.url

```
