### ISSUE TITLE
M6 - A2 - Develop connection and extraction methods, and finalize screen showing hourly CO2 avoided.

### ISSUE THREAD

**Issue by renovus** [Renovus-Tech/solarec-java#9]
This will make it possible to obtain grid emissions data to an hourly level, and show per hour how much a SolaREC user avoided in tons of CO2.

Testing of grid data over several weeks works properly in 100% of tests

**Comment by pferrariuy** [comment]
During development of issue #25 the `tech.renovus.solarec.scheduler.DataGridCheckScheduler` was developed to retrieve the information from the implemented `tech.renovus.solarec.grid.DataGridService`.
